### ISSUE TITLE
Issue with Cloning

### ISSUE THREAD

**Issue by Parnasuss-MD** [Kr4ken-9/DAB#45]
Hey @Kr4ken-9  I tried to clone the repo but got this error every time and not sure why or how I can fix this. I took out most of the numbers in the below error just in case it led to personal information or things I shouldn't be giving out since I'me kinda new to this stuff.

C:\Users\:black_large_square:>git clone git@github.com:Kr4ken-9/DAB
Cloning into 'DAB'...
The authenticity of host 'github.com (19:black_large_square:53.:black_large_square:3)' can't be established.
RSA key fingerprint is SHA:black_large_square:Thbg6kXUp:black_large_square:E1IGOCspRom:black_large_square:ARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])?
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by Kr4ken-9** [comment]
I'm honestly not sure what caused this error, Google might be more useful than me. You could try cloning via https though.

**Comment by Kr4ken-9** [comment]
There has been no followup for nearly a month, I am going to assume this has been solved.
