### ISSUE TITLE
Feature Request 

### ISSUE THREAD

**Issue by MagicXYZ** [Kr4ken-9/DAB#52]
Request?
- Pokecord custom catch list.

How it works?
- Catches the spawned poke if the poke is in the custom catch list file.
- Ignores the spawned poke if the poke is not in the custom catch list file.

**Comment by Kr4ken-9** [comment]
I added support for Pokemon whitelisting and blacklisting here: https://github.com/Kr4ken-9/DAB/commit/957596e880e035e9308627c8f04183c0815464f9

You will have to configure it manually but it should be pretty straightforward. You can take a look at the [docs](https://kr4ken-9.github.io/DAB/Pokecord.html) for more information.

I tested it lightly and it should work. Test it yourself and tell me if it works or not, and you can close this issue if it works for you.

**Comment by MagicXYZ** [comment]
Yup, it works! Thanks!
