### ISSUE TITLE
Feature Enchancement

### ISSUE THREAD

**Issue by MagicXYZ** [Kr4ken-9/DAB#53]
Make the pokecord catches to lowercase so that it looks more natural. 
For example from `p!catch Pikachu` to `p!catch pikachu`.

**Comment by Kr4ken-9** [comment]
I added this option in this commit: https://github.com/Kr4ken-9/DAB/commit/25b5751029cd5a6458defa884794aaf36c227914

I tested it, and it should work. You can close this issue if it does work for you.

Also, thank you for your suggestions! If you have any more, I will be happy to help you with them.

**Comment by MagicXYZ** [comment]
Thanks a lot! This works perfectly too!
