### ISSUE TITLE
Pokecord Bug

### ISSUE THREAD

**Issue by MagicXYZ** [Kr4ken-9/DAB#55]
Hashes for some of the Pokémons are outdated.
- For example: whenever Flabébé or Flapple spawns, it throws an error in the console, and hence doesn’t catch the poke. [There are more cases such as this one. I just can’t seem to remember their names.]
- Whenever Leavanny spawns, the bot detects it as Poipole, and hence executes the `p!catch Poipole` command instead of `p!catch Leavanny`.

**Comment by Kr4ken-9** [comment]
Can you upload the pictures for Flabébé and Flapple? It's possible they are using different pictures for those pokemon.

For some reason the hasher script records Leavanny's hash under Poipole's name, so that's why that happens. I will try to fix this shortly.

**Comment by Kr4ken-9** [comment]
I did some debugging and it is not a problem with the script, but with the dhash algorithm DAB uses. I am pretty sure there is a collision with Levanny's picture and Poipole's picture. So I am looking at options to use other algorithms maybe. Which is a shame, because dhash is the fastest algorithm.

**Comment by MagicXYZ** [comment]
Flapple: https://cdn.discordapp.com/attachments/386324037552308224/692810010274693181/PokecordSpawn.jpg

Flabebe: https://cdn.discordapp.com/attachments/482315290760314880/692799429740200047/PokecordSpawn.jpg

**Comment by Kr4ken-9** [comment]
Both of those images match the ones we are using to get the hash, so I don't think it is a problem with different images. If the error happens again, can you take a screenshot or copy paste so I can see it?

If we used a different algorithm, yes that is what it would mean. But there is a script to change the hashes, so it wouldn't be too much trouble for anyone. I am looking into a simpler solution in the meantime.

**Comment by MagicXYZ** [comment]
Alright! Thanks a lot! I’ll notify you if I ever again catch an error in the console.

**Comment by Kr4ken-9** [comment]
Thank you! I will push a fix for Leavanny and Poipole soon.
