### ISSUE TITLE
glitch 

### ISSUE THREAD

**Issue by ashishlodhi1234** [Kr4ken-9/DAB#56]
i am open mai.py file automated closed without reson

**Comment by Kr4ken-9** [comment]
Does it close immediately after opening it? Are you double-clicking it or running it the way you are supposed to, according to the README?

https://github.com/Kr4ken-9/DAB#how-do-i-use-it

**Comment by Kr4ken-9** [comment]
It has been a week with no response so I am going to close this issue and assume it's been solved
