### ISSUE TITLE
Proxy support?

### ISSUE THREAD

**Issue by bokja** [Kr4ken-9/DAB#65]
I mean is it possible to add proxy support to this would be great

**Comment by Kr4ken-9** [comment]
What is the use-case of a proxy? I get flagged by Discord using a VPN, so I would guess using a proxy would make you look suspicious.

To answer your question, it would be possible to add proxy support. However, I don't use them and am not familiar with them, so someone else would have to do it.

**Comment by bokja** [comment]
You can close this its already supporter nativily in discord.py
