### ISSUE TITLE
pokemon missing from database

### ISSUE THREAD

**Issue by ninfia123** [Kr4ken-9/DAB#67]
Previously if a Pokemon was missing it gave out the hash, so we were able to edit the correct hash in pokebois.jason
but now it says ``Hash:<built-in function hash>``, so i can't really do anything about this. 
Could you please update them whenever you get time, no rush

I am aware of the following missing/wrong hash pokemons:
floatzel, shellos, gastrodon, magmortar, basculin, frillish, jellicent, pyroar, meowstic, aegislash, cutiefly, cursola and magearna

And some new pokemons:
kubfu, urshifu, zarude, galarian slowpoke and galarian slowbro

copy pokecord's (now called pokerealm) ID: 665301904791699476

**Comment by Kr4ken-9** [comment]
I can fix the hash error very easily. The tools for scraping new pokemon are kind of ugly, I'll need to rewrite them or fix them up at least. This could take a while

**Comment by Kr4ken-9** [comment]
You can test out the fix for missing pokemon reporting in the latest commit:
https://github.com/Kr4ken-9/DAB/commit/a7b41204a4e2141c1250afa2bf4a3bb0e9fb4d1f

**Comment by circle134** [comment]
oh its showing the hash we can fix that ourselves now
and for the new pokemons its ok, take ur time 
ty
