### ISSUE TITLE
poketwo issue

### ISSUE THREAD

**Issue by meechypie** [Kr4ken-9/DAB#68]
@Kr4ken-9 Hey when i spawn pokemon via the message farming option it doesnt catch the pokemon for me on poketwo. Or am i doing it wrong? how exactly do i activate the poketwo script since it doesnt catch any pokes at all

**Comment by Kr4ken-9** [comment]
PokeTwo is not supported yet. When I was working on it, they had spawning disabled for whatever reason. I will have to look into it.

**Comment by meechypie** [comment]
> PokeTwo is not supported yet. When I was working on it, they had spawning disabled for whatever reason. I will have to look into it.

is there any other pokecord clone that is supported at the moment?

**Comment by Kr4ken-9** [comment]
There is one called PokeRealm which is supported. There are some missing pokemon that you can read about here: https://github.com/Kr4ken-9/DAB/issues/67

But otherwise I think it works pretty well.

**Comment by meechypie** [comment]
> There is one called PokeRealm which is supported. There are some missing pokemon that you can read about here: #67
> 
> But otherwise I think it works pretty well.

where can i find a invite link for the bot?

**Comment by meechypie** [comment]
is it possible for u to look into the captcha system of pokemeow?

**Comment by Kr4ken-9** [comment]
I am not familiar with their captcha system. I would have to look into it.

**Comment by Kr4ken-9** [comment]
Fixed in https://github.com/Kr4ken-9/DAB/commit/b4e31a77c8d97e3654cbc62d99e06754cdaed255
Worked fine except PokeTwo isn't using hidden characters like PokeRealm.
