### ISSUE TITLE
SOLVED

### ISSUE THREAD

**Issue by QTpie42** [Kr4ken-9/DAB#71]
How do we edit the message farming ability to allow us to switch it off and on, on command?

**Comment by Kr4ken-9** [comment]
At the moment there are no commands for this purpose, but it is a planned feature.

**Comment by meechypie** [comment]
is it possible for u to add a way to add different delays between different msgs?

**Comment by Kr4ken-9** [comment]
It is possible but I have no plans to implement it in the near future.
