### ISSUE TITLE
Missing Hash for Alolan Geodude

### ISSUE THREAD

**Issue by chanm123456** [Kr4ken-9/DAB#74]
0000000800064003200d396e18e39a993129324b33db261b8cf4108125100000
Alolan Geodude

**Comment by Kr4ken-9** [comment]
Updating all the pokemon hashes is on my to-do list. Might not happen soon though.

**Comment by Kr4ken-9** [comment]
This should have been fixed by @jan2705 in the latest commit. The hash matches to my knowledge, so I am going to close this issue.
