### ISSUE TITLE
missing hashes

### ISSUE THREAD

**Issue by ninfia123** [Kr4ken-9/DAB#81]
most of the spawn image hashes have been changed (80%) in pokerealm bot, maybe they made changes to images 
so could you maybe teach us how to update hashes, cuz it seems like this will happen often
thank you

**Comment by RizwanS1** [comment]
Tbh I think pokerealm just needs to edit a few hashes but, Poketwo needs a full edit for image hashes cuz of new images

**Comment by ninfia123** [comment]
> Tbh I think pokerealm just needs to edit a few hashes but, Poketwo needs a full edit for image hashes cuz of new images

oh yea the poketwo background?
pokerealm made changes too, like brightened the image a little or made them slightly bigger or blurry in some cases
it would be helpful to learn how to update hashes ourselves, I don't wanna bother Kr4ken again and again

**Comment by Kr4ken-9** [comment]
Is it possible for you to provide some example images from Pokerealm?

There is already some discussion on how to bypass Poketwo, so that should be relatively easy.

All the tools for hashing/scraping are in this directory: https://github.com/Kr4ken-9/DAB/tree/master/pokebad

They are written in python, so if you understand python they are also well documented and should be very useful for updating hashes by yourself.

**Comment by ninfia123** [comment]
> Is it possible for you to provide some example images from Pokerealm?

yes i got some like
old
![pokemon apple 2](https://user-images.githubusercontent.com/67867904/90476311-b5a80500-e142-11ea-8c69-f0a610ebb48a.png)
new
![pokemon apple 1](https://user-images.githubusercontent.com/67867904/90476265-9ad59080-e142-11ea-9d56-0731ea052938.png)
old
![pokemon turtwig old](https://user-images.githubusercontent.com/67867904/90476345-c2c4f400-e142-11ea-9a03-2e8fdcd0200f.png)
new
![pokemon turtwig new](https://user-images.githubusercontent.com/67867904/90476330-bc367c80-e142-11ea-8b23-fbd170cfe648.png)

the newer ones are little bright and have thicker outlines, they did i with every image, but for some the old hashes work (like turtwig)


> All the tools for hashing/scraping are in this directory: https://github.com/Kr4ken-9/DAB/tree/master/pokebad
>
> They are written in python, so if you understand python they are also well documented and should be very useful for updating hashes by yourself.

i just know little bout python, and there is a lot I don't understand, but i will look into it

**Comment by ninfia123** [comment]
oh by the way they fixed the blurred images

**Comment by Kr4ken-9** [comment]
Do you mean the images are no longer blurred?
The latest commit should've fixed detecting most of them: https://github.com/Kr4ken-9/DAB/commit/86a87a8c95933d65fbbf9885c91352ad3e15a6e4

**Comment by anas-p13** [comment]
yes most of them are solved
tysm
