### ISSUE TITLE
After the hash issue in pokerealm, DAB has been performing weakly

### ISSUE THREAD

**Issue by ninfia123** [Kr4ken-9/DAB#83]
so this problem arose immediately after pokerealm made changes to image  
but I managed to fix some common hashes manually (edit in pokebois.json) 
then after than dab takes a lot of time to catch, like it can't handle more than 1 server whereas it could do up to 5 servers earlier
It takes a second or 2 to catch a Pokemon, whereas previously it could catch up to 5 in a sec
its not really my connection issue, cuz i have noticed dab has started to consume lot of internet (x3 now)
I really think its the hash calculating problem or something
also could u please update the hashes too
thank you

**Comment by anas-p13** [comment]
hi
so after the latest commit, my catcher has been catching like it used too
tysm

**Comment by Kr4ken-9** [comment]
I'm glad it's working decently again
